server:
  port: 7777
eureka:
  client:
    # 是否将自己注册到 Eureka Server
    register-with-eureka: false
    # 是否从 Eureka Server 获取注册信息
    fetch-registry: false
    service-url:
      defaultZone: http://root:root@127.0.0.1:7777/eureka/
security:
  user:
    name: root
    password: root
