info:
  component: Zuul Server

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

hystrix:
  threadpool:
    default:
      coreSize: 300
      maxQueueSize: 200
      queueSizeRejectionThreshold: 150
  command:
    default:
      circuitBreaker:
        requestVolumeThreshold: 50
      execution:
        timeout:
          enabled: true
        isolation:
          strategy: THREAD
          semaphore:
            maxConcurrentRequests: 1000
          thread:
            timeoutInMilliseconds: 150000

ribbon:
  ConnectTimeout: 30000
  ReadTimeout: 30000
#  MaxAutoRetriesNextServer: 3

zuul:
  host:
    socket-timeout-millis: 30000
    connect-timeout-millis: 30000
  ignored-services: "*"
  routes:
    consumer:
      path: /consumer/**
      stripPrefix: true
      serviceId: consumer

logging:
  level:
    ROOT: INFO
    org.springframework.web: INFO

spring.resources.static-locations: classpath:/resources/,classpath:/static/,classpath:/public/,classpath:/templates/