spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
    virtual-host: /smart-community
#    通过实现ConfirmCallBack接口，消息发送到交换器Exchange后触发回调。
    publisher-confirms: true
#    通过实现ReturnCallback接口，如果消息从交换器发送到对应队列失败时触发（比如根据发送消息时指定的routingKey找不到队列时会触发）
    publisher-returns: true
#    # 对 rabbitmqTemplate 进行监听,当消息由于server的原因无法到达queue时，就会被监听到，以便执行ReturnCallback方法
    ## 默认为false,Server端会自动删除不可达消息
    template:
      mandatory: true
    listener:
      simple:
        # 消费端手动确认
        acknowledge-mode: manual
        # 并发消费 最小线程5最大10
        concurrency: 5
        max-concurrency: 10