spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: root
    timeout: 5000
    pool:
      max-active: 200
      max-wait: -1
      min-idle: 0
      max-idle: 10

permission:
  key: PERMISSION_KEY
userinfo:
  key: userInfo:key-